### ISSUE TITLE
Wrong version in source code

### ISSUE THREAD

**Issue by llaville** [jguadagno/bootstrapThemeSwitcher#5]
Current source code specify 1.0.3, while latest release version is 1.1.4

https://github.com/jguadagno/bootstrapThemeSwitcher/blob/master/jquery.bootstrapThemeSwitcher.js#L2

BTW, thanks for your plugin, it's really cool and useful :)

**Comment by jguadagno** [comment]
I synchronized the licenses with the last release v1.1.5
